name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    env:
      CXX: clang++-22
      CC: clang-22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM 22
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y cmake ninja-build ccache

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os}}-ccache-

      - name: Configure CMake
        run: cmake --preset debug

      - name: Build
        run: cmake --build build/debug

      - name: Run tests
        run: ctest --test-dir build/debug --output-on-failure

  formatting:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM 22
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y clang-format-22

      - name: Run clang-format
        run: find src include -type f \( -name "*.cpp" -o -name "*.h" \) | xargs clang-format-22 --dry-run --Werror

  static-analysis:
    runs-on: ubuntu-24.04
    env:
      CXX: clang++-22
      CC: clang-22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM 22
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y cmake ninja-build clang-tidy-22

      - name: Configure CMake
        run: cmake --preset debug

      - name: Run clang-tidy
        run: find src -name "*.cpp" | xargs clang-tidy-22 -p build/debug